### PR TITLE
Remove telemetry datastructures

### PR DESCRIPTION
**Pull request by amilcarlucas**
Hello Andy,

I decided to remove the remains of the telemetry data-structures. This should save some memory.

### CODE REVIEW

**Comment by andyp1per** [comment]
@amilcarlucas This is a fairly significant change to a PR that's already going to be hard to test. I would prefer to get a review and plan going forward before combining it with this.

**Comment by amilcarlucas** [comment]
@andyp1per I am fine with that. Thanks.

**Comment by andyp1per** [comment]
@amilcarlucas Can you rebase?

**Comment by amilcarlucas** [comment]
done

**Comment by amilcarlucas** [comment]
This saves 1472 bytes on Copter (Durandal)

**Review by andyp1per — APPROVED** [review]

**Pull request merged**
